dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.12.x
env:
  GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod

script:
- go list -m all  
- go get ./...  
- go list -m all
- make test
- make vet

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
